In [7]:
import  numpy as np
c=np.array([[1,2,3,4],[4,5,6,7],[np.nan,8,9,10]])
np.save('save_1.npy',c)#保存为save_1.npy文件

#保存为save_1.npy文件

In [8]:
f=np.load('save_1.npy')

In [9]:
f

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [nan,  8.,  9., 10.]])

In [10]:
c=np.array([[1,2,3,4],[4,5,6,7],[np.nan,8,9,10]])
a=np.array([[1,3],[4,2],[8,6]])
np.savez('save_2.npz',a,c)

f=np.load('save_2.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'save_2.npy'

In [11]:
import numpy as np

c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [np.nan, 8, 9, 10]])
a = np.array([[1, 3], [4, 2], [8, 6]])

np.savez('save_2.npz', a=a, c=c)

data = np.load('save_2.npz')

a_loaded = data['a']
c_loaded = data['c']

print(a_loaded)
print(c_loaded)

[[1 3]
 [4 2]
 [8 6]]
[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [nan  8.  9. 10.]]


In [13]:
data
data['a']

array([[1, 3],
       [4, 2],
       [8, 6]])

In [14]:
import numpy as np

c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [np.nan, 8, 9, 10]])
a = np.array([[1, 3], [4, 2], [8, 6]])

np.savetxt('save_text.out',c)

In [15]:
np.loadtxt('save_text.out')

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [nan,  8.,  9., 10.]])

三行两列两个

In [16]:
d=c.reshape((2,3,2))#三行两列两个
print(d)

[[[ 1.  2.]
  [ 3.  4.]
  [ 4.  5.]]

 [[ 6.  7.]
  [nan  8.]
  [ 9. 10.]]]


CSV文件只能存储一维数组和二维数组
np.savetxt()和 np.loadtxt()方法只能存取一维数组和二维数组

In [17]:
np.savetxt('save_text.out',d)

ValueError: Expected 1D or 2D array, got 3D array instead

In [20]:
import numpy as np

c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [np.nan, 8, 9, 10]])
d=c.reshape((2,3,2))
d

In [21]:
d.tofile('1.dat',sep=',',format='%s')

In [23]:
print(d.tofile('1.dat',sep=',',format='%s'))

None


In [27]:
print(np.fromfile('1.dat',dtype=np.float64,count=-1,sep=','))

[ 1.  2.  3.  4.  4.  5.  6.  7. nan  8.  9. 10.]


In [30]:
np.fromfile('1.dat',dtype=np.float64,count=-1,sep=',').reshape(2,3,2)

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [nan,  8.],
        [ 9., 10.]]])