In [1]:
import numpy as np
a=np.array([[1,3],[4,2],[8,6]])
a

array([[1, 3],
       [4, 2],
       [8, 6]])

In [2]:
np.sort(a,axis=1)#对行排序

array([[1, 3],
       [2, 4],
       [6, 8]])

In [3]:
a#a没有改变

array([[1, 3],
       [4, 2],
       [8, 6]])

In [4]:
np.sort(a,axis=0)#对列排序

array([[1, 2],
       [4, 3],
       [8, 6]])

In [6]:
a.sort()
a

array([[1, 3],
       [2, 4],
       [6, 8]])

In [9]:
j=np.argsort(a)
j

array([[0, 1],
       [1, 0],
       [1, 0]])

In [7]:
a=np.array([[1,3],[4,2],[8,6]])
a

array([[1, 3],
       [4, 2],
       [8, 6]])

In [8]:
j=np.argsort(a)
j

array([[0, 1],
       [1, 0],
       [1, 0]])

In [11]:
a=np.array([[1,3],[4,2],[8,6]])
a

array([[1, 3],
       [4, 2],
       [8, 6]])

查找最大值

In [12]:
np.argmax(a,axis=0)

array([2, 2])

In [13]:
a.max()

8

In [14]:
a.max(axis=0)

array([8, 6])

In [15]:
a.max(axis=1)

array([3, 4, 8])