数组的切分

In [21]:
import numpy as np
c=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(c)
print("*"*70)
np.vsplit(c,3)#将数组a在水平方向切成3等份
print(np.vsplit(c,3))
print("*"*70)
print(np.hsplit(c,2))#将数组a在垂直方向切成2等份

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
**********************************************************************
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]]), array([[ 7,  8,  9, 10]])]
**********************************************************************
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])]


#缺失值的检测

In [25]:
import numpy as np
c=np.array([[1,2,3,4],[4,5,6,7],[np.nan,8,9,10]])
c

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [nan,  8.,  9., 10.]])

In [26]:
import numpy as np
c=np.array([[1,2,3,4],[4,5,6,7],[np.nan,8,9,10]])
print(c)

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [nan  8.  9. 10.]]


#这个函数用来检测是不是空值nan

In [27]:
np.isnan(c)

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

#把nan替换成0

In [28]:
np.nan_to_num(c)

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [ 0.,  8.,  9., 10.]])

#删除数组的行或列

In [33]:
import numpy as  np
a=np.array([[1,2],[3,4],[5,6]])
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
import numpy as  np
a=np.array([[1,2],[3,4],[5,6]])
a
np.delete(a,1,axis=0)

array([[1, 2],
       [5, 6]])

In [35]:
import numpy as  np
a=np.array([[1,2],[3,4],[5,6]])
a
np.delete(a,1,axis=0)
np.delete(a,(1,2),0)

array([[1, 2]])

In [36]:
import numpy as  np
a=np.array([[1,2],[3,4],[5,6]])
a
np.delete(a,1,axis=1)

array([[1],
       [3],
       [5]])

In [39]:
import numpy as  np
a=np.array([[1,2],[3,4],[5,6]])
a=np.split(a,2,axis=1)
a

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]