#数组的复制

In [3]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

view是对数组a的浅复制，两个数组不同，但是数据共享
copy是对数组a的深复制，两个数组不同，数据不共享


In [4]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
c=a.view()
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
d=a.copy()
d

array([[1, 2],
       [3, 4],
       [5, 6]])

#查看acd的内存地址

In [7]:
id(a)

4619912176

In [8]:
id(c)

4619912272

In [9]:
id(d)

4619009648

In [10]:
a[1,0]=0
a

array([[1, 2],
       [0, 4],
       [5, 6]])

In [11]:
c

array([[1, 2],
       [0, 4],
       [5, 6]])

In [12]:
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
c[1,0]=3
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])